[target."wasm32-unknown-unknown"]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory",
             "-C", "link-arg=--initial-memory=65536",
             "-C", "link-arg=--max-memory=65536",
             "-C", "link-arg=-zstack-size=4096"]
